In [ ]:
import os
os.environ['KAGGLE_USERNAME'] = "divyarathi31"
os.environ['KAGGLE_KEY'] = "814901b6ab29e003e55b0dbb726e0c52"
!kaggle datasets download -d praveengovi/emotions-dataset-for-nlp

  0% 0.00/721k [00:00<?, ?B/s]
100% 721k/721k [00:00<00:00, 49.6MB/s]


In [ ]:
!unzip "/content/emotions-dataset-for-nlp.zip"

Archive:  /content/emotions-dataset-for-nlp.zip
  inflating: test.txt                
  inflating: train.txt               
  inflating: val.txt                 


In [ ]:
import numpy as np 
import pandas as pd 

In [ ]:
test = pd.read_csv('/content/test.txt',sep=";",header=None)
train = pd.read_csv('/content/train.txt',sep=";",header=None)
val = pd.read_csv('/content/val.txt',sep=";",header=None)

In [ ]:
test.head()

0        1
0  im feeling rather rotten so im not very ambiti...  sadness
1          im updating my blog because i feel shitty  sadness
2  i never make her separate from me because i do...  sadness
3  i left with my bouquet of red and yellow tulip...      joy
4    i was feeling a little vain when i did this one  sadness

In [ ]:
train.head()

0        1
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [ ]:
val.head()

0        1
0  im feeling quite sad and sorry for myself but ...  sadness
1  i feel like i am still looking at a blank canv...  sadness
2                     i feel like a faithful servant     love
3                  i am just feeling cranky and blue    anger
4  i can have for a treat or if i am feeling festive      joy

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16000 entries, 0 to 15999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       16000 non-null  object
 1   1       16000 non-null  object
dtypes: object(2)
memory usage: 250.1+ KB


In [ ]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       2000 non-null   object
 1   1       2000 non-null   object
dtypes: object(2)
memory usage: 31.4+ KB


In [ ]:
val.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       2000 non-null   object
 1   1       2000 non-null   object
dtypes: object(2)
memory usage: 31.4+ KB


# **Preparing the Dataset**

In [ ]:
# Splitting X and Y
x_train = train.iloc[:,0] 
y_train = train.iloc[:,1] 

x_test = test.iloc[:,0] 
y_test = test.iloc[:,1] 

x_val = test.iloc[:,0] 
y_val = test.iloc[:,1] 

x_train,y_train = np.array(x_train),np.array(y_train)
x_test,y_test = np.array(x_test),np.array(y_test)
x_val,y_val = np.array(x_val),np.array(y_val)

print(x_train.shape,"|",y_train.shape)
print(x_test.shape,"|",y_test.shape)
print(x_val.shape,"|",y_val.shape)

(16000,) | (16000,)
(2000,) | (2000,)
(2000,) | (2000,)


In [ ]:
# Convert y to integers.
print(train.iloc[:,1].value_counts())

int_y_train = []
int_y_test = []
int_y_val = []

for l in y_train:
    
    if l == "joy":        
        int_y_train.append(0)   
    if l == "sadness":       
        int_y_train.append(1)            
    if l == "anger":      
        int_y_train.append(2)      
    if l == "fear":
        int_y_train.append(3)
    if l == "love":
        int_y_train.append(4)
    if l == "surprise":
        int_y_train.append(5)
        
        
for l in y_test:
    
    if l == "joy":        
        int_y_test.append(0)    
    if l == "sadness":       
        int_y_test.append(1)            
    if l == "anger":      
        int_y_test.append(2)      
    if l == "fear":
        int_y_test.append(3)
    if l == "love":
        int_y_test.append(4)
    if l == "surprise":
        int_y_test.append(5)
        
for l in y_val:
    
    if l == "joy":        
        int_y_val.append(0)    
    if l == "sadness":       
        int_y_val.append(1)            
    if l == "anger":      
        int_y_val.append(2)      
    if l == "fear":
        int_y_val.append(3)
    if l == "love":
        int_y_val.append(4)
    if l == "surprise":
        int_y_val.append(5)

int_y_train,int_y_test,int_y_val = np.array(int_y_train),np.array(int_y_test),np.array(int_y_val)

from sklearn import preprocessing
from keras.utils import np_utils

le = preprocessing.LabelEncoder()
le.fit(int_y_train)

encoded_y_train = le.transform(int_y_train)
encoded_y_test = le.transform(int_y_test)
encoded_y_val = le.transform(int_y_val)

encoded_y_train = np_utils.to_categorical(encoded_y_train)
encoded_y_test = np_utils.to_categorical(encoded_y_test)
encoded_y_val = np_utils.to_categorical(encoded_y_val)

print(encoded_y_train)

print(int_y_train[:10])

joy         5362
sadness     4666
anger       2159
fear        1937
love        1304
surprise     572
Name: 1, dtype: int64
[[0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 ...
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]]
[1 1 2 4 2 1 5 3 0 4]


# **Tokenization**

In [ ]:
x_train[0]

'i didnt feel humiliated'

In [ ]:
x_test[1]

'im updating my blog because i feel shitty'

In [ ]:
x_val[1]

'im updating my blog because i feel shitty'

In [ ]:
import nltk
nltk.download('stopwords')
from tensorflow.python.keras.preprocessing.text import Tokenizer
from tensorflow.python.keras.preprocessing.sequence import pad_sequences
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
stopwords = stopwords.words('english')
stopwords[:5]

['i', 'me', 'my', 'myself', 'we']

In [ ]:
x_train_cl = []
x_test_cl = []
x_val_cl = []


# Deleting stopwords
for text in x_train:
    
    text = text.split()
    text = [word for word in text if word not in stopwords]
    text = " ".join(text)
    x_train_cl.append(text)

for text in x_test:
    
    text = text.split()
    text = [word for word in text if word not in stopwords]
    text = " ".join(text)
    x_test_cl.append(text)

for text in x_val:
    
    text = text.split()
    text = [word for word in text if word not in stopwords]
    text = " ".join(text)
    x_val_cl.append(text)
    
x_train,x_test,x_val = np.array(x_train_cl),np.array(x_test_cl),np.array(x_val_cl)

# We use total_text for fitting tokenizer in general 
total_text = np.concatenate((x_train,x_test,x_val),axis=0)

num_words = 2000

tokenizer = Tokenizer(num_words = num_words) 

tokenizer.fit_on_texts(total_text)
list(tokenizer.word_index)[:10]

['feel',
 'feeling',
 'like',
 'im',
 'really',
 'know',
 'time',
 'get',
 'little',
 'people']

In [ ]:
# Tokenizing everything

x_train_token = tokenizer.texts_to_sequences(x_train)
x_test_token = tokenizer.texts_to_sequences(x_test)
x_val_token = tokenizer.texts_to_sequences(x_val)

total_token = np.concatenate((x_train_token,x_test_token,x_val_token),axis=0)

In [ ]:
# Padding
print(np.mean([len(text) for text in total_token]))

7.6699


In [ ]:
x_train_pad = pad_sequences(x_train_token,20) 
x_test_pad = pad_sequences(x_test_token,20)
x_val_pad = pad_sequences(x_val_token,20)

print(x_train_pad[0],end="\n-------------------------------------------------------------------------\n")
print(x_train_pad[1])

[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0  50
   1 495]
-------------------------------------------------------------------------
[   0    0    0    0    0    0    0    0    0    0    0    0   30    2
  464  425   44   54 1573 1304]


# **Modeling and Predicting**

In [ ]:
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense,CuDNNGRU,Embedding,Bidirectional


model = Sequential()

model.add(Embedding(input_dim=2000
                   ,output_dim=100
                   ,input_length=20))

model.add(Bidirectional(CuDNNGRU(units=16,return_sequences=True)))

model.add(Bidirectional(CuDNNGRU(units=8)))

model.add(Dense(6,activation="softmax"))

model.compile(loss="categorical_crossentropy",optimizer="rmsprop",metrics=["accuracy"])

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 20, 100)           200000    
_________________________________________________________________
bidirectional (Bidirectional (None, 20, 32)            11328     
_________________________________________________________________
bidirectional_1 (Bidirection (None, 16)                2016      
_________________________________________________________________
dense (Dense)                (None, 6)                 102       
Total params: 213,446
Trainable params: 213,446
Non-trainable params: 0
_________________________________________________________________


In [ ]:
print(x_train_pad.shape)
print(y_train.shape)
model.fit(x_train_pad, encoded_y_train, epochs=10, batch_size=20) 

(16000, 20)
(16000,)
Epoch 1/10
800/800 [==============================] - 7s 9ms/step - loss: 1.0392 - accuracy: 0.6116
Epoch 2/10
800/800 [==============================] - 7s 9ms/step - loss: 0.3402 - accuracy: 0.8874
Epoch 3/10
800/800 [==============================] - 7s 9ms/step - loss: 0.2067 - accuracy: 0.9216
Epoch 4/10
800/800 [==============================] - 7s 9ms/step - loss: 0.1645 - accuracy: 0.9337
Epoch 5/10
800/800 [==============================] - 7s 9ms/step - loss: 0.1417 - accuracy: 0.9414
Epoch 6/10
800/800 [==============================] - 7s 9ms/step - loss: 0.1302 - accuracy: 0.9464
Epoch 7/10
800/800 [==============================] - 7s 9ms/step - loss: 0.1207 - accuracy: 0.9506
Epoch 8/10
800/800 [==============================] - 7s 9ms/step - loss: 0.1127 - accuracy: 0.9534
Epoch 9/10
800/800 [==============================] - 8s 9ms/step - loss: 0.1043 - accuracy: 0.9570
Epoch 10/10
800/800 [==============================] - 7s 9ms/step - loss: 0.09

In [ ]:
preds = model.predict_classes(x_test_pad)
from sklearn.metrics import accuracy_score

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


In [ ]:
accuracy_score(preds,int_y_test)

0.9215